In [1]:
import numpy as np

## Exercice 0

In [36]:
v1=np.array([5,9,1,3])
v2=2*np.ones((1,20))
v3=np.linspace(1,16,16)    #v3=np.arange(1,17)
v4=np.arange(28,11,-2)

## Exercice 1

In [47]:
def matrice_carre(n,a,b):
    M=(a-b)*np.eye(n)+b*np.ones((n,n))
    return M
#test
matrice_carre(5,2,11)

array([[ 2., 11., 11., 11., 11.],
       [11.,  2., 11., 11., 11.],
       [11., 11.,  2., 11., 11.],
       [11., 11., 11.,  2., 11.],
       [11., 11., 11., 11.,  2.]])

## Exercice 2

In [50]:
A=np.arange(0,11,0.1)
len(A)

110

In [53]:
A=np.linspace(0,10,110)
A[:10]

array([0.        , 0.09174312, 0.18348624, 0.27522936, 0.36697248,
       0.4587156 , 0.55045872, 0.64220183, 0.73394495, 0.82568807])

In [65]:
def tridiag(a, b, c,n):
    d=b*np.ones(n)
    l=a*np.ones(n-1)
    u=c*np.ones(n-1)
    return np.diag(l, -1) + np.diag(d, 0) + np.diag(u, 1)
#test
tridiag(-1,4,-1,6)

array([[ 4., -1.,  0.,  0.,  0.,  0.],
       [-1.,  4., -1.,  0.,  0.,  0.],
       [ 0., -1.,  4., -1.,  0.,  0.],
       [ 0.,  0., -1.,  4., -1.,  0.],
       [ 0.,  0.,  0., -1.,  4., -1.],
       [ 0.,  0.,  0.,  0., -1.,  4.]])

## Exercice 4

In [71]:
def somme(n):
    return np.sum(np.arange(1,n+1))
#test
somme(5)

15

In [72]:
def somme2(n):
    return np.sum(1/np.arange(1,n+1)**2)
#test
somme2(5)

1.4636111111111112

## Exercice 5

In [100]:
def normes(cord):
    m,n=cord.shape
    if m==2:
        L=[np.linalg.norm(cord[:,i]) for i in range(n)]
        return np.array(L)
    elif n==2:
        L=[np.linalg.norm(cord[i,:]) for i in range(m)]
        return np.array(L)
#test
cord=np.arange(1,11).reshape(-1,2)
normes(cord)

array([ 2.23606798,  5.        ,  7.81024968, 10.63014581, 13.45362405])

## Exercice 6

In [96]:
A=np.random.randint(1,36,(4,9))

In [98]:
A[:,0],A[:,8],A[0,:],A[3,:]=0,0,0,0
A

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 27, 31, 15, 18, 16, 24, 24,  0],
       [ 0, 20, 19,  6,  4,  9,  5, 26,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])